# Generated by Django 4.0.3 on 2022-03-21 13:43

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveIntegerField(choices=[(200, '200'), (100, '100')])),
                ('structure', models.CharField(max_length=256)),
                ('flavor', models.CharField(max_length=256)),
                ('img', models.ImageField(blank=True, null=True, upload_to='static')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('count', models.IntegerField(db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Свеча',
                'verbose_name_plural': 'Свечи',
                'ordering': ('count',),
            },
        ),
        migrations.CreateModel(
            name='UUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('address', models.CharField(default='None', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candle_t', models.CharField(choices=[('фигура', 'фигура'), ('стандартная', 'стандартная')], max_length=255)),
                ('candle_color', models.CharField(choices=[('белый', 'белый'), ('желтый', 'желтый'), ('черный', 'черный')], max_length=255)),
                ('candle_flavor', models.CharField(choices=[('яблочный пирог', 'яблочный пирог'), ('черный кокос', 'черный кокос'), ('вечер у камина', 'вечер у камина'), ('ягодный пунш', 'ягодный пунш'), ('сумеречный лес', 'сумеречный лес')], max_length=255)),
                ('candle_volume', models.PositiveIntegerField(choices=[(200, 200), (100, 100)])),
                ('status', models.CharField(choices=[('формируется', 'формируется'), ('отправлено', 'отправлено')], db_index=True, default='формируется', max_length=255)),
                ('created_order', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ordering', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('status', 'created_order'),
            },
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveIntegerField(choices=[(200, '200'), (100, '100')])),
                ('structure', models.CharField(max_length=256)),
                ('flavor', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('формируется', 'формируется'), ('отправлено', 'отправлено')], db_index=True, default='формируется', max_length=255)),
                ('created_order', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_buy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'ordering': ('status', 'created_order'),
            },
        ),
    ]
