# Generated by Django 4.0.3 on 2022-03-19 22:53

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveIntegerField(choices=[(200, '200'), (100, '100')])),
                ('structure', models.CharField(max_length=256)),
                ('flavor', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('count', models.IntegerField(db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Свеча',
                'verbose_name_plural': 'Свечи',
                'ordering': ('count',),
            },
        ),
        migrations.CreateModel(
            name='UUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=12, unique=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candle_t', models.PositiveIntegerField(choices=[(1, 'figure'), (2, 'candle_standart')])),
                ('candle_color', models.PositiveIntegerField(choices=[(1, 'WHITE'), (2, 'YELLOW'), (3, 'BLACK')])),
                ('candle_flavor', models.PositiveIntegerField(choices=[(1, 'яблочный пирог'), (2, 'черный кокос'), (3, 'вечер у камина'), (4, 'ягодный пунш'), (5, 'сумеречный лес')])),
                ('candle_volume', models.PositiveIntegerField(choices=[(1, '200'), (2, '100')])),
                ('status', models.PositiveIntegerField(choices=[(1, 'In processing'), (2, 'sent')], db_index=True, default='1')),
                ('created_order', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ordering', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('status', 'created_order'),
            },
        ),
    ]
