# Generated by Django 4.0.3 on 2022-03-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='Отсутствует', max_length=255),
        ),
    ]
