# Generated by Django 4.0.3 on 2022-03-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uuser',
            name='address',
            field=models.CharField(default='Отсутствует', max_length=255, null=True),
        ),
    ]
