# Generated by Django 4.0.3 on 2022-03-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In processing', 1), ('sent', 2)], db_index=True, default='1', max_length=255),
        ),
    ]
