# Generated by Django 4.0.3 on 2022-03-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_uuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='address',
            field=models.CharField(default='Отсутствует', max_length=255),
        ),
        migrations.AddField(
            model_name='buy',
            name='price',
            field=models.DecimalField(decimal_places=2, default=14.0, max_digits=5),
            preserve_default=False,
        ),
    ]
