# Generated by Django 4.0.3 on 2022-03-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_buy_address_buy_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buy',
            options={'ordering': ('status', 'created_order'), 'verbose_name': 'Стандартные', 'verbose_name_plural': 'Стандартные'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('status', 'created_order'), 'verbose_name': 'Кастом', 'verbose_name_plural': 'Кастом'},
        ),
        migrations.AlterField(
            model_name='uuser',
            name='phone',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
